name: Build and Test

on:
  workflow_dispatch:
  pull_request:
    branches: [ master ]
    paths:
      - 'src/**'
      - 'include/**'
      - 'external/**'
      - 'tests/**'
      - 'CMakeLists.txt'
      - 'conanfile.py'
      - 'conan/**'
      - 'version.txt'
      - '.conan/**'
      - '.github/workflows/**'

jobs:
  build-test:
    runs-on: ${{ matrix.runs_on }}
    strategy:
      matrix:
        include:
          - os: windows
            runs_on: windows-2022
            configure_preset: conan-default
          - os: linux
            runs_on: ubuntu-latest
            configure_preset: conan-release

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Setup Conan
      uses: conan-io/setup-conan@v1
      with:
        cache_packages: true

    - name: Add private artifactory
      run: |
        conan remote add artifactory ${{ vars.ARTIFACTORY_URL }} --force
        conan remote login artifactory ci -p ${{ secrets.ARTIFACTS_TOKEN }}

    - name: Configure and build
      shell: bash
      run: |
        conan install . -pr .conan/profile -s build_type=Release --build=missing
        cmake --preset ${{ matrix.configure_preset }}
        cmake --build --preset conan-release --config Release

  test:
    runs-on: ${{ matrix.runs_on }}
    strategy:
      matrix:
        include:
          - os: windows
            runs_on: windows-2022
            configure_preset: conan-default
            build_preset: conan-release
            test_preset: conan-release
            build_type: Release
          - os: linux
            runs_on: ubuntu-latest
            configure_preset: conan-release
            build_preset: conan-release
            test_preset: conan-release
            build_type: Release

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Setup Conan
      uses: conan-io/setup-conan@v1
      with:
        cache_packages: true

    - name: Add private artifactory
      run: |
        conan remote add artifactory ${{ vars.ARTIFACTORY_URL }} --force
        conan remote login artifactory ci -p ${{ secrets.ARTIFACTS_TOKEN }}

    - name: Build and run tests
      working-directory: tests
      shell: bash
      run: |
        conan install . -pr ../.conan/profile -s build_type=${{ matrix.build_type }} --build=missing
        cmake --preset ${{ matrix.configure_preset }}
        cmake --build --preset ${{ matrix.build_preset }}
        ctest --preset ${{ matrix.test_preset }} --output-on-failure
