// @PROJECT_NAME@ — a minimal Moth game: a window, a scene, and a moving square.
// Generated by `moth new`. Replace GameScene with your own game logic.

#include <moth_graphics/game/game.h>

#include <cmath>

using namespace moth::gfx;
using namespace moth::gfx::game;
using namespace moth::core;

namespace {
    class GameScene : public Scene {
    public:
        void Update(float dt) override {
            m_time += dt;
        }

        void Draw(IGraphics& graphics) override {
            graphics.SetColor(Color{ 0.10f, 0.12f, 0.16f, 1.0f });
            graphics.DrawFillRectF(FloatRect{ { 0.0f, 0.0f }, { 1280.0f, 720.0f } });

            float const x = 400.0f + 300.0f * std::sin(m_time * 2.0f);
            graphics.SetColor(Color{ 1.0f, 0.4f, 0.2f, 1.0f });
            graphics.DrawFillRectF(FloatRect{ { x - 32.0f, 328.0f }, { x + 32.0f, 392.0f } });
        }

    private:
        float m_time = 0.0f;
    };
}

int main() {
    Game game{ "My Game", 1280, 720 };
    return game.Run(std::make_unique<GameScene>());
}
